Add the possibility to get segments corresponding to the four quadrant of VLT aperture.
ehpor/hcipy pull request #101
Opened 2021-04-11 11:56 UTC by npourre

Hi! I am a student in astrophysics in Grenoble, France. In a project I am working on, I need to separate the quadrant of the VLT aperture. I have been in touch with Emiel that told me he was interested in merging my solution to get the VLT segmented aperture.

I chose a geometric approach, computing the coordinates of the lines drawn by the spiders and applying conditions (above this line, below this line...) to define the quadrants. Quadrants can be created contiguous or separated by a space corresponding to spiders width (with_segment_gaps=True or False). It works perfectly for my usage but I hope it is suitable for a merging in HCIPy. Feel free to ask me changes! It is my first GitHub branch :D.

Best regards,

Nicolas

2022-08-04 01:50 UTC, ehpor commented
I apparently had an almost-finished PR review pending, but not posted, on this PR. I'll post that review right after this comment for completeness. I still agree with most of those comments, but I don't think it's appropriate nor fair to require you finish the PR after this long of a delay, unless you want to.

@npourre I propose to either
1. merge this PR as is, and I'll take care of the cleanup in a subsequent PR, or
2. keep this PR open, and you do the cleanup before merging.

Let me know what you want to do.

2022-08-04 01:51 UTC, ehpor reviewed
Also, testing the segmentation in CI is missing, resulting in the lost test coverage as reported by codecov.

2022-08-05 09:28 UTC, npourre commented
> I apparently had an almost-finished PR review pending, but not posted, on this PR. I'll post that review right after this comment for completeness. I still agree with most of those comments, but I don't think it's appropriate nor fair to require you finish the PR after this long of a delay, unless you want to.
> 
> @npourre I propose to either
> 
>     1. merge this PR as is, and I'll take care of the cleanup in a subsequent PR, or
> 
>     2. keep this PR open, and you do the cleanup before merging.
> 
> 
> Let me know what you want to do.

@ehpor , I would be glad to do the cleanup myself. So, keep the PR open and I will deal with it.
I will be on leave for the next three weeks. So I might not make all the changes before September.

2022-08-30 08:22 UTC, npourre commented
I cleaned and reshaped the segments computation following your guidelines. It is much shorter indeed!
Feel free to ask me for more changes or to modify the code yourself.

2022-08-30 21:47 UTC, ehpor requested changes
This looks great! Even cleaner than I thought it would be! Thanks!

Only a few things remaining:

- [ ] Rebase your fork and fix the merge conflict. It's a trivial one, but git is choking on it. Let me know if you're unsure on how to do this.
- [ ] Fix the flake8 errors. These are mostly small whitespace issues. See [here](https://github.com/ehpor/hcipy/runs/8102251261) or run flake8 locally.
- [ ] Add a check for the segmentation in the Pytest. This should be as simple as adding `check_segmentation=True` to that function call, similar to other segmentation checks, but I might be mistaken on that.

2022-08-30 21:47 UTC, ehpor commented on hcipy/aperture/realistic.py
> +	with_segment_gaps : boolean
This argument was removed from the signature. Remove it from the docstring as well.

2022-10-17 00:47 UTC, ehpor approved these changes
LGTM. Thanks for getting this to the finish line. :tada:

2022-10-17 00:47 UTC, merged

2022-10-17 06:11 UTC, npourre commented
Great! Thanks a lot Emiel for giving it the last push. :smiley: