fix pwfs tutorial
ehpor/hcipy pull request #110
Opened 2021-08-11 19:03 UTC by syhaffert

I changed the pyramid wavefront sensor tutorial to make it compatible with the new pwfs interface. It now runs again.

2021-08-14 05:44 UTC, ehpor requested changes
Just the same PEP8 formatting error four times in a row. Otherwise looks perfect to me.

For a future PR: I saw that this tutorial still uses the old way of animation. That should be switched over sometime to the new way (see the EFC tutorial for what I mean with "the new way"). No priority on that at all; just wanted to put it down somewhere.

2021-08-14 05:44 UTC, ehpor commented on doc/tutorial_notebooks/PyramidWFS/PyramidWFS.ipynb
> +    "    PSF = prop( deformable_mirror(wf) ).power\n",
Fix spaces after parentheses.

2021-08-14 05:44 UTC, ehpor commented on doc/tutorial_notebooks/PyramidWFS/PyramidWFS.ipynb
> +    "    im3 = imshow_field( np.log10(PSF / norm), vmax=0, vmin=-5, cmap='inferno')\n",
Fix spaces after parentheses.

2021-08-14 05:44 UTC, ehpor commented on doc/tutorial_notebooks/PyramidWFS/PyramidWFS.ipynb
> +    "        psf = prop( deformable_mirror(wf) ).power\n",
Fix spaces after parentheses.

2021-08-14 05:44 UTC, ehpor commented on doc/tutorial_notebooks/PyramidWFS/PyramidWFS.ipynb
> +    "        im3.set_data(*focal_grid.separated_coords, np.log10( psf.shaped / norm ) )\n",
Fix spaces after parentheses.

2021-08-15 04:02 UTC, syhaffert commented
Yeah, I went through the tutorial and there are many things I would do differently now. I think at a certain point we should probably overhaul a couple of these tutorials and make them uniform?

2021-08-16 17:57 UTC, ehpor approved these changes

2021-08-16 17:58 UTC, merged