Deterministic atmospheric phase screens
ehpor/hcipy pull request #173
Opened 2023-03-15 22:05 UTC by ehpor

This PR adds seeds to the spectral noise factories and the atmospheric phase screens. This makes these atmospheric phase screens deterministic.

Fixes #169.

2023-03-28 20:31 UTC, syhaffert commented on hcipy/atmosphere/finite_atmospheric_layer.py
The FiniteAtmosphericLayer also needs the self.rng in case people use that class directly. The behavior might be undefined at the moment if we call the reset method and self.rng is not set.

2023-03-28 20:31 UTC, syhaffert requested changes
Changes look good to me except for the one comment I had.

2023-03-29 01:54 UTC, ehpor commented on hcipy/atmosphere/finite_atmospheric_layer.py
The `self.rng` gets created during the call to `FiniteAtmosphericLayer.reset()` does it not? That function gets called during `__init__()`.

For `InfiniteAtmosphericLayer`, the `self.rng` is already needed when creating the stencils, which requires me to already define it before the call to `reset()`.

2023-03-29 17:26 UTC, syhaffert commented on hcipy/atmosphere/finite_atmospheric_layer.py
I missed the call to self.reset in the init(). okay this is resolved.

2023-03-29 20:54 UTC, ivalaginja commented
I haven't had the time to look into this yet, so please go ahead without my review unless you insist.

2023-03-29 23:27 UTC, merged