Dispersion optics
ehpor/hcipy pull request #176
Opened 2023-04-03 20:29 UTC by syhaffert

I have added some optics that introduce dispersion (prism and grating) and some helper functions. These will be useful for simulating spectrographs and ADCs. I have tried to make comprehensive tests and document all functionality.

2023-04-06 20:30 UTC, ehpor requested changes
Overall looks like a worthwhile change and definitely something that I'll use myself instead of the few rudimentary classes that I built personally and never bothered to clean up.

Some PEP8 stylistic changes regarding assignment of lambdas to variables. These should be replaced by a function definition. There are a few more than I indicated, so look yourself at other places where you made the same mistake. Also some missing units in the docstrings (also way more than I indicated; just look through all the places where there is an angle and add "radians").

2023-04-07 17:20 UTC, syhaffert commented
I have addressed your comments and made some changes. I think it should be ready now.

2023-04-07 23:35 UTC, ehpor requested changes
The rest looks good.

2023-04-07 23:35 UTC, ehpor commented on hcipy/optics/dispersion_optics.py
> +		The wedge angle of the prism.
Still a missing unit here.

2023-04-07 23:39 UTC, ehpor approved these changes
Thanks for all these new optical elements!

2023-04-08 00:32 UTC, merged