Lyot coronagraph fix
ehpor/hcipy pull request #217
Opened 2023-11-12 22:47 UTC by syhaffert

This pull request fixes the bug in #177. I added an explicit parameter to pass the coronagraphic focal grid to the lyot coronagraph. And I have also changed how the grid is determined when an optical element is passed into the function. The function now works with any derivative of the Apodizer class, which should capture 95% of all cases. The other cases will still work if they pass the focal grid explicitely.

2023-11-13 01:53 UTC, ehpor commented
@syhaffert I've too noticed that tabs still exist in some files. Apparently #196 didn't catch all files (even though it was a replace-all). I'm doing a second PR for that. So please keep the indentation as is. You'll have to a rebase, dropping the whitespace commit (currently the last one).

I'll look at the rest of the PR tomorrow.

2023-11-13 02:43 UTC, syhaffert commented
okay done 😄

2023-11-13 07:29 UTC, ehpor commented
@syhaffert Nope, not by adding a commit. That still destroys Git Blame. I said, do it with a rebase.

2023-12-05 20:05 UTC, ehpor requested changes
If you add a sentence explaining that using this new parameter is part of a workaround, like put that in a `.. notes::` section in the docstring, then I'm fine with it.

Also, what about renaming it to `focal_plane_mask_grid`. Coronagraphic focal grid doesn't feel specific enough to me.

2023-12-14 15:07 UTC, ehpor approved these changes

2023-12-14 15:08 UTC, merged