Fiber nulling module
ehpor/hcipy pull request #230
Opened 2024-07-24 22:47 UTC by yinzi-xin

This adds a fiber nulling module with generic/custom fiber nuller, vortex fiber nuller, and photonic lantern nuller classes.

2024-11-16 22:17 UTC, ehpor commented
Discussed this offline yesterday with @yinzi-xin. We discussed issues and fixes for those issues.

(Just making a note of this for the sake of documentation.)

2024-11-19 21:33 UTC, yinzi-xin commented
I think I'm done making edits to the code. Can you run the tests again that identify where all the issues (e.g. missing whitespaces) are?

2024-11-19 22:49 UTC, ehpor commented
@yinzi-xin They are running now.

2024-11-20 05:55 UTC, ehpor commented
Test failures are unrelated to this PR and will be fixed by #245 and #246.

That being said: there should be some tests for the new code that you're adding @yinzi-xin. I'll have to think what constitutes a correct test. Probably injecting one of the modes of the lantern and confirming that that mode is completely injected into one of the output waveguides. And for the vortex fiber nuller: testing the fact that it suppresses all light (within a tolerance) on a symmetric pupil (say, circular).

2024-11-27 01:04 UTC, ehpor requested changes
Only one comment remaining. Otherwise this is perfect.

I made some formatting changes, so you'll have to `git pull` before you make more changes. @yinzi-xin

2024-11-27 01:04 UTC, ehpor commented on hcipy/optics/photonic_lantern.py
> +    def __init__(self, lantern_modes, normalize_modes=True):
`normalize_modes`? It's not used by the function, and it's not in the docstring.

2024-11-27 17:07 UTC, merged

2024-11-27 17:52 UTC, ehpor commented
@yinzi-xin Thanks for your first contribution! 🎉